### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by dbu** [indigophp/cookie-consent-bundle#3]
I notice that the configuration (include separate javascript, target of the "more information" link) can only be set from within twig. I would think there is rarely a case where you need different behaviour on different pages of the same application, so putting this into the symfony configuration and inject it from there into the twig extension would probably make more sense.

**Comment by sagikazarmark** [comment]
Actually I just completely removed the symfony configuration. Do you think it was a bad idea? :stuck_out_tongue:

**Comment by sagikazarmark** [comment]
Probably it would be better to have config and make it configurable from Twig as well.

**Comment by dbu** [comment]
you could have global configuration and use that as default and allow
overriding from twig if you think there is a use case for needing to
change the settings on a specific page.
